name: envattrs workflow

on: push

permissions:
  actions: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pytest:
    name: Run pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          curl -sSL https://install.python-poetry.org | python -
        env:
          POETRY_VERSION: 1.3.1
        shell: bash
      - run: poetry install
        shell: bash
      - name: Run pytest
        run: |
          poetry run pytest \
          --cov=envattrs --cov-branch \
          --cov-report=html:reports/coverage/ \
          --junit-xml=reports/results.xml
        shell: bash
      - name: Store test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.python-version }}
          path: reports/results.xml
      - name: Store test coverage
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage-${{ matrix.python-version }}
          path: reports/coverage/

  pre-commit:
    name: Run pre-commit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
            python-version: 3.7
      - uses: pre-commit/actions@v3.0.0
